### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by louisdh**
This PR updates the license of OpenTerm to prevent clones on the App Store. The chosen license approach is based on [VLC for iOS](https://github.com/videolan/vlc-ios). This change requires approval from all contributors, which at the time of writing are:
@IMcD23 
@holzschu 
@palmin 
@filippocld 
@mecid 
@hevey 
@maxkatzmann 
@simpaa 
@reden87 
@BasThomas 

Please reply on this PR with any concerns you may have and wether you approve of this change. Thank you.

### CODE REVIEW

**Comment by filippocld** [comment]
I Approve this licence

**Comment by LeoNatan** [comment]
Also please notify pending pull requests of this change and ask for their permission also. Just to be sure 🙂

**Comment by BasThomas** [comment]
👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by palmin** [comment]
I also approve the licensing change. 

Not sure how the Mozilla license prevents other people from putting the app on the store, while still letting @louisdh do it. Are we sure VLC isn’t doing something extra?

**Comment by simpaa** [comment]
I approve the license change. 👍

**Comment by louisdh** [comment]
@palmin I'm not sure how the "bi-licensed under the GPLv2 (or later) and the MPLv2" works, but it sure seems to work for VLC.

**Comment by LeoNatan** [comment]
@palmin The MPL license takes care of any potential issues with Apple's App Store. It is still a copyleft license which requires that any redistribution must provide source code and remain under the same license.

If this is not the desired outcome—@louisdh if you want sole ability to release on the App Store—I suggest an even more stricter dual license, where only you are granted proprietary license while everyone else is only granted GPLv2.

**Comment by LeoNatan** [comment]
It seems the MPL relicense of VLC for iOS was triggered by some GPL code owners not agreeing with VLC being released on the Apple App Store. So those portions of the code were rewritten under the joint license.

**Comment by louisdh** [comment]
So it's safe for OpenTerm to drop the MPL part? Making it licensed under GPLv2?

**Comment by LeoNatan** [comment]
Depending on interpretations, it may not be safe _for you_ on the App Store. That is why you can license it under proprietary license for yourself. Is this the desired result—only you being able to release on the App Store?

**Comment by louisdh** [comment]
Yes, that would be ideal in my opinion. Having a single, official, OpenTerm on the App Store. Unless of course someone fundamentally changed an OpenTerm fork and redistributed it, that would still be fine. But right now there's a clone on the app store with just a different icon and name.

**Comment by LeoNatan** [comment]
Regarding the clone, it is important to note that you can do little do drop it. The code, at the time of the fork, was under a permissive license, and you cannot take that back. Even if you relicense—to whatever you choose—those forks are still legal.

**Comment by louisdh** [comment]
@LeoNatan Sure, what's done is done. But let's prevent it from happening with future versions.

So shall I change the license to this?
```
This software is licensed under the GPLv2 (or later).
 
 Any commit to this repository implicitely allows Louis D'hauwe to relicense
 this software to any OSI-approved license, without prior consent.
```

**Comment by LeoNatan** [comment]
You should change it to include the proprietary license as well, otherwise you will have trouble accepting contributions made under GPLv2 (as you are not the owner of that code).

**Comment by louisdh** [comment]
It might be easiest to change it to GPL v3.0, as [Blink does](https://github.com/blinksh/blink/blob/master/COPYING). 

This would create the following conditions for redistribution:
* License and copyright notice
* State changes
* Disclose source
* Same license

Which seems fair in my opinion.

**Comment by LeoNatan** [comment]
If you create a CLA, which your contributors must sign before contributing, GPLv3 is perfectly fine because you can then relicense the source as the copyright owner.

**Comment by LeoNatan** [comment]
Software licenses are hard. 😂

**Comment by LeoNatan** [comment]
After all, this is what brought VLC for iOS down all those years ago. GPL contributors refused to allow it on the App Store. Theoretically, any Blink contributor is capable of removing it from the storm and creating a legal storm. Do you want that?

**Comment by louisdh** [comment]
I’d like to follow VLC’s example (bi-licensed under the GPLv2 and the MPLv2). So the current PR stands. I don’t particularly want to disallow all redistributions, but the current clones in the App Store would be in violation of GPLv2/MPLv2, while the current MIT license makes them legal.

**Comment by louisdh** [comment]
So if we can get the approval of the following contributors, this is good to go.
@IMcD23
@holzschu
@mecid
@hevey
@maxkatzmann
@reden87

**Comment by IMcD23** [comment]
Does this license change require any license changes to third party libraries used by OpenTerm (such as TabView)?

**Comment by louisdh** [comment]
It does not to my knowledge. @LeoNatan right?

**Comment by LeoNatan** [comment]
No. This is only for the using software. There is absolutely no problem using permissive licensed open sources or a need to change.

**Comment by IMcD23** [comment]
I approve of this change.

**Comment by hevey** [comment]
I'm cool with this

**Comment by holzschu** [comment]
I approve of this change.
(and I thank @IMcD23 for asking the question I was going to ask).

**Comment by reden87** [comment]
I approve also! 🙂

**Comment by mecid** [comment]
I approve the license change.

**Comment by louisdh** [comment]
All right, case closed! 👨‍⚖️

**Pull request merged**
